import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ContactUsSection from '../Components/ContactSection'
import Banner from '../Components/Banner'
// our-domain.com/Home
export default function Contact() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner heading="Contact Us" />
        <ContactUsSection/>
      </main>
    
    </div>
  )
}
