import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../Components/Banner'
import Education from '../Components/OurWork/Education'
import Testimonials from '../Components/Testimonial'
import axios from 'axios'
// our-domain.com/Home
export default function EducationMain({test}) {
  // console.log("SADSADSADSAD", test)
  return (
    <div className={styles.container}>
      <Head>
        <title>Education</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Banner heading="Education" />
          <Education/>
          <Testimonials data={test}  />
      </main>
    
    </div>
  )
}
