import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../Components/Banner'
import PhotographySection from '../Components/PhotographySection'
import OurSampleWork from '../Components/OurSampleWork'
// our-domain.com/Home
export default function GolfCourseVirtualTour() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Photography</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner heading="PHOTOGRAHY" />
        <PhotographySection />
        <OurSampleWork name="PGS" />
      </main>
    </div>
  )
}
