import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from '../Components/Banner'
import RealEstate from '../Components/OurWork/RealEstate'
import Testimonials from '../Components/Testimonial'

import axios from 'axios'
// our-domain.com/Home
export default function RealEstateMain({test}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Banner heading="Real Estate" />
          <RealEstate/>
          <Testimonials data={test}  />
      </main>
    
    </div>
  )
}
