import Head from 'next/head'
import styles from '../../../styles/Home.module.css'
import Banner from '../../../Components/Banner'
import axios from 'axios'
import { useRouter } from "next/router"
// import Education from '../Components/OurWork/Education'
import Testimonials from '../../../Components/Testimonial'
import { useEffect, useState } from 'react'
import OurWorkSection from '../../../Components/OurWorkSection'
// our-domain.com/Home
export default function DynamicComponent({test}) {
  const [array, onChangeArray] = useState([])
  //  a("SADSADSADSAD")
  var router = useRouter()
  const { id,name } = router.query
  useEffect(() => {
    axios.get(`https://webprojectmockup.com/custom/mass_interact/public/api/our_work/${id}`)
    .then((response) => {
     //  a(Id, "AHSAN")
       if(response.data.success){
        console.log(response.data.data, "GGG")
        onChangeArray(response.data.data)
        //  a(response.data.data)
       }
    
    })
    .catch((error)=>{
       console.log(error);
    });
  },[id])
  

  return (
    <div className={styles.container}>
      <Head>
        <title>{name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      {/* <h1>A</h1> */}
        <Banner heading={name} />
          {/* <Banner heading="Education" />
          <Education/>
        
          <Testimonials data={test}  /> */}
   
          <OurWorkSection data={array} />
        
       
        <Testimonials data={test}  /> 
      </main>
    
    </div>
  )
}
